### ISSUE TITLE
Non-critical misprint at description

### ISSUE THREAD

**Issue by Lur3out** [Cyber-Guy1/BlackDragon#2]
Well, i found one misprint (non critical, but :) ) at Black-Dragon, line 849.

Expected: "[3] OS, Version, & Script Scannin**g** & Traceroute [Most Common 1000 Port]"
Actual: "[3] OS, Version, & Script Scannin & Traceroute [Most Common 1000 Port]"

**Comment by Cyber-Guy1** [comment]
Thanks

**Comment by Cyber-Guy1** [comment]
<h1>Fixed Now</h1>

<small>Appreciated, Thanks For Your Effort<br>Keep Secure ;)</small>
