### ISSUE TITLE
Not able to install massdns

### ISSUE THREAD

**Issue by anubhavsinghhacker** [Cyber-Guy1/BlackDragon#3]
Because when we are cloning repo of massdns and while doing cd we going to  `~/BlackDragon/BD-Tools/` and not going to this directory  `~/BlackDragon/BD-Tools/massdns `which creates the issue

code :- 
```
printf "\n\n\e[7m Installing Massdns \e[27m\n\n"
git clone https://github.com/blechschmidt/massdns.git
cd ~/BlackDragon/BD-Tools/
sudo make
```

code should be :-
```
printf "\n\n\e[7m Installing Massdns \e[27m\n\n"
git clone https://github.com/blechschmidt/massdns.git
cd ~/BlackDragon/BD-Tools/massdns
sudo make
```

**Comment by Cyber-Guy1** [comment]
Thanks For Your Report, We Will Fix It ASAP

**Comment by Cyber-Guy1** [comment]
<h1>Fixed Now</h1>

<small>Appreciated, Thanks For Your Effort<br>Keep Secure ;)</small>
