### ISSUE TITLE
While installing requirements.txt of Sublist3r getting error

### ISSUE THREAD

**Issue by anubhavsinghhacker** [Cyber-Guy1/BlackDragon#4]
You are using pip which is not available now. So the solution is use **pip3** instead of **pip**

code :- 
```
cd Sublist3r*
pip install -r requirements.txt
```

code should be :-

```
cd Sublist3r*
pip3 install -r requirements.txt
```

**Comment by Cyber-Guy1** [comment]
Thank You For Your Report, We Will Fix It ASAP

**Comment by Cyber-Guy1** [comment]
<h1>Fixed Now</h1>

<small>Appreciated, Thanks For Your Effort<br>Keep Secure ;)</small>
