### ISSUE TITLE
How to add Github tokens & Wordlist ? 

### ISSUE THREAD

**Issue by stish834** [Cyber-Guy1/BlackDragon#5]
token

![Screenshot 2021-05-22 18:04:36](https://user-images.githubusercontent.com/31948359/119226774-7a4ec280-bb28-11eb-971f-41fa4d2be7e7.png)

wordlist

![Screenshot 2021-05-22 18:06:08](https://user-images.githubusercontent.com/31948359/119226775-7c188600-bb28-11eb-8f6d-4b9e2e24f6a6.png)

**Comment by Cyber-Guy1** [comment]
Did You Mean That You Want It Hardcoded Or How Generally Add It ?

**Comment by stish834** [comment]
I don't want to put GitHub code all the times & wordlist all the time 

so I want to put the code & wordlist path 

so I don't have to do them manually all the time while scanning.

by the way, thank you for the beautiful repo

**Comment by zAbuQasem** [comment]
you can use this to get the paths then just supply it to the commad easily.
in special cases you might have to make new varaibles & if statements
```bash
while getopts "w:t:" arg; do
  case $arg in
    w)
      w=$(OPTARG) 
      ;;
    t)
      t=$(OPTARG)
      ;;
  esac
done```

**Comment by Cyber-Guy1** [comment]
In Coming Version You Will Be Able To Assign Them Easily, You Can Also Do Like Mr. @zAbuQasem In The Script Until The New Version Released

**Comment by Cyber-Guy1** [comment]
You can hardcode it or use switches as @zAbuQasem explained upper.

Thank you
